### ISSUE TITLE
Theme slows down Obsidian Dataview Rendering

### ISSUE THREAD

**Issue by hpr1999** [Akifyss/obsidian-border#102]
Hi - this is a marvelous theme.

---

I have found a bizzarre performance problem.
This theme causes rendering of some Obsidian-Dataview-Blocks to be much, _much_ slower.
However, this _only_ happens, when the other plugin "Emoji Shortcodes" is enabled.

I only found this by making a test vault and then porting over the plugins from my test-vault one-by-one. 
I'm not sure if there's anything for you to do here, but I still wanted to raise the issue, as this problem does not appear with the default or any other theme I tested.

I have attached the [test vault.](https://github.com/Akifyss/obsidian-border/files/12643224/test.zip)

---

To test, first open Dataview.md and let it render with the default theme. 
Then change to the Border theme, switch to another file and switch back to Dataview.md. 

Both render times should be alright, if not quick.

Then, go into Settings and enable the "Emoji Shortcodes" community plugin.
Now, if you switch to another file and then back to Dataview.md, the render should take a very long time to complete.

Switch back to the default theme and render once more - this will also take **much longer** than without "Emoji Shortcodes", but with the Border theme, it takes more than twice as long on my machine.

I will probably also raise this with Emoji Shortcodes / Dataview, but it's curious that this theme makes it much worse as well.

---

Once more, thanks for the great theme =)

**Comment by Akifyss** [comment]
Unfortunately, this issue is directly tied to performance issues with this theme. To fix this theme's performance issues, you can only manually remove some code such as the "hover line indicator" and the "auto hide" sections.

![image](https://github.com/Akifyss/obsidian-border/assets/23567154/b2a9f417-d88d-4732-bd8d-cd1f1e23f2a0)
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/02c92830-cd4d-4b68-a23f-76f261a8d440)
