### ISSUE TITLE
Path doesn't work for background image

### ISSUE THREAD

**Issue by AYA-123** [Akifyss/obsidian-border#121]
In style settings, when setting the underlying background, you can set to customize css, and set url. This url only works for web based images, and not local images

**Comment by Akifyss** [comment]
This is some potentially useful information that I found on the web:

To reference local files in CSS using the `url()` function, you would use a relative or absolute file path. Here are examples for both Windows and MacOS:

```css
/* Relative path */
background-image: url('images/background.jpg');

/* Absolute path (Windows) */
background-image: url('C:/Users/Username/Documents/website/images/background.jpg');

/* Absolute path (MacOS) */
background-image: url('/Users/username/documents/website/images/background.jpg');
```

The following points should be considered:

1. **File Path**: The file path should be correct. If the CSS file is in the same directory as the image, you only need the image file name. If the CSS file is in a different directory, you'll need to use a relative or absolute path.

2. **Case Sensitivity**: MacOS file systems are usually case-sensitive. Ensure that your file paths match the case of your actual files.

3. **Spaces in File Names**: If your file or folder names include spaces, either remove the spaces or use quotes around the path in your `url()` function.

4. **Absolute vs. Relative Paths**: Absolute paths start from the root directory and specify the complete file path. Relative paths are relative to the current file location. Relative paths are generally preferred for web development because they allow for greater flexibility if you need to move files around.

5. **Permission**: Make sure the file has the appropriate permissions to be read.

6. **Browser Restrictions**: Some browsers may have security restrictions that prevent local file paths from being used, especially when the HTML file is also a local file (file protocol). These restrictions can usually be bypassed in a server environment.

**Comment by Akifyss** [comment]
If the previous method still doesn't work, you can consider converting the local image to base64 format:  https://www.base64-image.de/

**Comment by Leo310** [comment]
> 1. **File Path**: The file path should be correct. If the CSS file is in the same directory as the image, you only need the image file name. If the CSS file is in a different directory, you'll need to use a relative or absolute path.

Which directory would that be? I tried out the themes/Border and the plugins/obsidian-style-settings directory. None of them worked.
