### ISSUE TITLE
Just an idea to improve the focus mode =)

### ISSUE THREAD

**Issue by lucasbcgeo** [Akifyss/obsidian-border#202]
https://discord.com/channels/686053708261228577/771575014382108672/1209220823102267404

instead the whole line/paragraph what about this?

=)

**Comment by Akifyss** [comment]
Thank you for the suggestion, it's great, but I found that the CSS theme might not be able to achieve this effect. I now think this might be the effect of a plugin because in later messages, the author shared several plugins related to focus mode:
https://discord.com/channels/686053708261228577/744933215063638183/1209239318900514927

**Comment by lucasbcgeo** [comment]
Ok! Thanks for the answers and the plugins tips. I've made anothers suggestions but now in the right place hehehehe
