### ISSUE TITLE
Tag colors in dataloom revert to dark mode when light mode is active

### ISSUE THREAD

**Issue by Arnoud-B** [Akifyss/obsidian-border#277]
Tag colors in dataloom revert to dark mode after restarting Obsidian, making the tags very hard to read. Note that when you switch themes to Border without restarting Obsidian, everything looks fine. When they are showing in the wrong mode, switching to dark mode and then back to light mode, the tags are shown in the correct colors again. This is only a temporary fix though, as the incorrect colors are shown again the next time Obsidian is started.

Themes like Minimal and Things do not have this issue. I'm not sure whether it's a dataloom issue or Border issue, so I also reported it to dataloom: https://github.com/trey-wallis/obsidian-dataloom/issues/535.

**Comment by Akifyss** [comment]
It can be reproduced, but the colors return to normal after a few seconds. The cause is still unknown because there is no mention of dataloom in the CSS code. Even deleting all CSS styles from the theme doesn't solve the problem; however, removing this style settings section does resolve it:
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/d28771ad-e5f5-4d11-b755-bd31abdf526c)

This is quite unusual because previously, all the theme bugs I encountered were usually related to the CSS part. Currently, I don't know the reason and am unable to resolve it. Sorry.
