### ISSUE TITLE
ipad OS

### ISSUE THREAD

**Issue by Arman-Username** [Akifyss/obsidian-border#324]
some of the customized css dose not work in ipad os. 

for example underlying background. 

i turned on card view pad version in style setting too.

**Comment by Arman-Username** [comment]
I think no change can be done in background except for global background. on ipad os obviously, everything is great on windows.

**Comment by Akifyss** [comment]
Indeed, some settings are not yet functional on mobile devices. The current theme is primarily designed for the Windows platform. Due to the significant differences between mobile and Windows platforms, I currently do not have the capacity to adjust these style parameters for mobile compatibility. Sorry
