### ISSUE TITLE
[BUG] Empty dataview query looks strange inside callouts

### ISSUE THREAD

**Issue by decatetsu** [Akifyss/obsidian-border#45]
I have this look. Maybe making borders thinner or making box smaller would be solution.

![image](https://user-images.githubusercontent.com/56955307/222171958-30dd6f58-9215-4ddf-800a-9148b08a0d2c.png)

**Comment by Akifyss** [comment]
I have noticed that this problem seems to exist in the default theme and many others. 
This is a CSS snippet that needs to be imported manually, and you can adjust it as you wish in Style Settings.

[dataview-error-box-adjust.zip](https://github.com/Akifyss/obsidian-border/files/10863666/dataview-error-box-adjust.zip)

**Comment by decatetsu** [comment]
Thank you!
