### ISSUE TITLE
Middle pane css settings don't work with stacked tabs

### ISSUE THREAD

**Issue by AYA-123** [Akifyss/obsidian-border#76]
When using style settings, for the background of the middle pane, and when you have stacked tabs enabled, the settings don't apply, and only when it is in normal mode (not stacked tabs) does the CSS apply

**Comment by Akifyss** [comment]
Sorry, but custom css is not allowed for the background of stacked tabs (but background colors are customizable). Because if custom css is allowed, it may result in multiple tabs with transparent backgrounds stacked on top of each other in some cases, and you can't even read the words, like this:
![image](https://github.com/Akifyss/obsidian-border/assets/23567154/b8f62e41-5e08-4b2e-91a5-1126e12a0d2a)
